export const EVENT_TYPES = {
  MEMORY_CREATED: "MEMORY_CREATED",
  QUESTION_COMPLETED: "QUESTION_COMPLETED",
  DREAM_COMPLETED: "DREAM_COMPLETED",
  IMPORTANT_DAY_CREATED: "IMPORTANT_DAY_CREATED",
  IMPORTANT_DAY_REACHED: "IMPORTANT_DAY_REACHED",
  TIME_CAPSULE_CREATED: "TIME_CAPSULE_CREATED",
  TIME_CAPSULE_OPENED: "TIME_CAPSULE_OPENED",
  OPEN_WHEN_CREATED: "OPEN_WHEN_CREATED",
  OPEN_WHEN_OPENED: "OPEN_WHEN_OPENED",
  DATE_ACTIVITY_COMPLETED: "DATE_ACTIVITY_COMPLETED",
} as const

export type EventType = keyof typeof EVENT_TYPES
